name: Test workflow
runs:
  using: "composite"
  steps:
    - name: Install Rust (nightly)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-08-10
    - name: Cargo test (miri)
      shell: bash
      run: |
        # Install and run miri tests
        cargo clean
        rustup component add --toolchain nightly-2025-08-10 miri
        # This somehow prints errors in CI that don't show up locally
        RUSTFLAGS=-Awarnings cargo +nightly-2025-08-10 miri test -p deno_core
