name: Test workflow
runs:
  using: "composite"
  steps:
    - name: Install Rust (nightly)
      uses: dtolnay/rust-toolchain@nightly
    - name: Cargo test (miri)
      shell: bash
      run: |
        # Install and run miri tests
        rustup component add --toolchain nightly miri
        # This somehow prints errors in CI that don't show up locally
        RUSTFLAGS=-Awarnings cargo +nightly miri test -p deno_core
