# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "serde_v8_utilities"
version = "0.3.0"
edition = "2024"
publish = false

[lib]
path = "lib.rs"

[dependencies]
v8.workspace = true
