# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "serde_v8_utilities"
version = "0.3.0"
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dependencies]
v8.workspace = true
