name: Test workflow
runs:
  using: "composite"
  steps:
    - name: Install valgrind
      shell: bash
      run: |
        # Installing packages
        sudo rm /var/lib/man-db/auto-update || true
        sudo apt-get install -y --no-install-recommends valgrind
    - name: Cargo test (valgrind)
      shell: bash
      run: |
        # --error-exitcode=1 
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="valgrind --error-exitcode=0 --leak-check=no --gen-suppressions=all --log-file=memcheck.log" \
          cargo test --release
        cat memcheck.log
