# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "serde_v8"
version = "0.191.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Rust to V8 serialization and deserialization"

[lib]
path = "lib.rs"

[dependencies]
num-bigint.workspace = true
serde.workspace = true
smallvec = { workspace = true, features = ["union"] }
thiserror.workspace = true
v8.workspace = true

[dev-dependencies]
bencher.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
serde_v8_utilities = { path = "./utilities" }

[[example]]
name = "basic"
