name: CI

on: [push, pull_request]

jobs:
  compute-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read-jobs.outputs.matrix }}
    steps:
      # https://github.com/marketplace/actions/query-yaml-config-as-outputs
      - name: Read job configuration
        uses: cloudposse/github-action-yaml-config-query@main
        id: read-jobs
        with:
          # Extract the jobs, then combine them with the os/uses line to build an array of 'includes' lines for the
          # matrix below
          query: "{ matrix: [. | to_entries[] | . as $entry | .value.jobs[] | { os: $entry.key, uses: $entry.value.uses, job: . }] }"
          config: |-
            linux:
              uses: ubuntu-latest
              jobs: [lint, lint-deps, test, test-miri]
            macos:
              uses: macOS-latest
              jobs: [lint, test]
            windows:
              uses: windows-2019
              jobs: [lint, test]

  top:
    name: build-${{ matrix.os }}
    needs: compute-jobs
    if: |
      (github.event_name == 'push' || !startsWith(github.event.pull_request.head.label, 'denoland:'))
      && github.ref_name != 'deno_core'
      && !startsWith(github.ref, 'refs/tags/deno/')
    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      job: ${{ matrix.job }}
    strategy:
      matrix:
        include: ${{ fromJSON(jobs.compute-jobs.outputs.matrix) }}
