name: ci

on: [push, pull_request]

jobs:
  top:
    name: deno_core-${{ matrix.os }}
    if: |
      (github.event_name == 'push' || !startsWith(github.event.pull_request.head.label, 'denoland:'))
      && github.ref_name != 'deno_core'
      && !startsWith(github.ref, 'refs/tags/deno/')
    uses: ./.github/workflows/ci-top.yml
    with:
      os: ${{ matrix.os }}
      job: ${{ matrix.job }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-2019]
        job: [test, lint]
