name: version_bump

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: "Kind of release"
        default: "minor"
        type: choice
        options:
          - minor
        required: true

jobs:
  build:
    name: version bump
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DENOBOT_PAT }}
          submodules: recursive

      - uses: denoland/setup-deno@v1
      - uses: dsherret/rust-toolchain-file@v1

      - name: Create PR for release
        env:
          GITHUB_TOKEN: ${{ secrets.DENOBOT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
        run: |
          git remote add upstream https://github.com/denoland/deno
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          deno run -A ./tools/create_pr_for_release.ts
